### ISSUE TITLE
Is this project intended to be built under "PlatformIO" - or in Arduino?

### ISSUE THREAD

**Issue by seamusdemora** [maxgerhardt/pio-picosleep#1]
@maxgerhardt : 

I'm still a bit confused wrt "PlatformIO", and I was just getting started with Arduino - so you are moving a bit fast for me to keep up...  please bear with me.

I gather from comments you've made that the code in this repo. supersedes the [code you posted here](https://github.com/earlephilhower/arduino-pico/issues/2528#issuecomment-2466951767) - or perhaps it's more correct to say that code was not intended to be built in the Arduino environment? ... Have I got that correct so far?  

Also, I gather the code here in this repo is intended to be used in the "PlatformIO" environment... is that correct? 

I'll just pause a moment here to say I'm willing to try anything, but my first preference would be to have something I can use in the Arduino-Pico environment. You made some comments [here](https://github.com/earlephilhower/arduino-pico/discussions/2601#discussioncomment-11245947) that ***suggest*** I may be able to do this in the Arduino-Pico environment: 

>It should work the same in the Arduino IDE if you open the main.cpp as main.ino in it, and set the USB stack to "None". I uploaded using a Debugprobe on Pico (CMSIS-DAP) and measure the VBUS line with my Nordic PPK2's Ammeter, which was fed externally by the Debugprobe's VBUS. 

* I've no idea what CMSIS-DAP is. 
* I do have a [Debug Probe](https://www.raspberrypi.com/products/debug-probe/).
* I do not have a PPK2 ammeter, and will forego making current measurements for the time being... I just want to see some working code! 

All that said, can you walk me through what I need to do to get your code working and uploaded to the Pico from Arduino-Pico using the standard USB connection?

**Comment by maxgerhardt** [comment]
You can flash another Pico with the https://github.com/raspberrypi/debugprobe/releases firmware and it will become a CMSIS-DAP device, which is a standardized debugging adapter. It can flash another Pico via its SWD pins, as explained in.

A "Debug Probe" *is* running the debug probe firmware, and thus is a CMSIS-DAP.

You can upload the firmware via the standard USB connection. Just note that the firmware itself does not open a USB serial port, so it will not print anything, it will just go to sleep when its being sent a UART character. So, to be able to test anything, you would very much need a device which can send that UART data; which is what a debug probe can also do. (it's a dual USB device: one CMSIS-DAP interface, one USB-to-serial adapter) 

Lots of this is documented in https://arduino-pico.readthedocs.io/en/latest/platformio.html and the therein linked docs.

You do not need PlatformIO for this. You can copy paste all needed source files into one directory, rename `main.cpp` to `main.ino`and open that in the Arduino IDE and flash it. However, the files in this project are meant as a PlatformIO project.

**Comment by seamusdemora** [comment]
Thanks @maxgerhardt  -  I'll try this asap  :)
